#!/bin/bash

classes=(DAW Project Track Playlist Clip Send)
classes+=(AudioEngine BufferManager AudioBuffer MessageQueue)
classes+=(web/Server web/Connection web/Request)
classes+=(APIHandler APIHandlers)
classes+=(AudioFile OpenAudioFile WAVFile RIFF)
classes+=(AudioFileRead)
classes+=(JSONParser FieldParser ProjectReader Base64 Logger)
classes+=(Process GetPBHeadProcess SeekProcess SupplyReadsProcess InstallProjectProcess)
classes+=(SendMeteringProcess)
classes+=(SelectInterfaceProcess)
classes+=(MutatingProcess)
classes+=(SetTrackGainProcess SetTrackNameProcess)
classes+=(AudioSystem AudioInterface)
classes+=(ALSAAudioSystem ALSAAudioInterface)
classes+=(IndentedOStream)
files=()
files+=(main.cpp)

for class in "${classes[@]}"; do
	files+=(${class}.h)
	files+=(${class}.cpp)
	done

files+=(Message.h AudioTypes.h Amp.h)
files+=(html/index.html html/dawlet.css html/dawlet.js)
js_classes=(Keys Actions SVGTemplate Track Knob MouseTracker dB)
for class in "${js_classes[@]}"; do
	files+=(html/${class}.js)
	done
files+=(Makefile edit-all)

$EDITOR "${files[@]}"

