#!/bin/bash

classes=(Project Track Playlist Send AudioEngine BufferManager AudioBuffer MessageQueue)
classes+=(web/Server web/Connection web/Request)
classes+=(JSONParser FieldParser Logger)
files=()
files+=(main.cpp)

for class in "${classes[@]}"; do
	files+=(${class}.h)
	files+=(${class}.cpp)
	done

files+=(Message.h AudioTypes.h Amp.h)
files+=(Makefile edit-all)

$EDITOR "${files[@]}"

