#!/usr/bin/env bash

classes=(DAW Project Track Playlist Clip Send)
classes+=(AudioEngine BufferManager AudioBuffer MessageQueue)
classes+=(web/Server web/Connection web/Request)
classes+=(APIHandler APIHandlers)
classes+=(AudioFile OpenAudioFile WAVFile RIFF SampleConversion)
classes+=(AudioFileRead Recorder RecordBuffers StartRecordingProcess RecordingClip)
classes+=(JSONParser FieldParser ProjectReader Base64 Logger Stats)
classes+=(Process SeekProcess SupplyReadsProcess InstallProjectProcess)
classes+=(GetProcess GetPBHeadProcess GetStatsProcess)
classes+=(SendMeteringProcess)
classes+=(SelectInterfaceProcess)
classes+=(MutatingProcess SetTrackStateProcesses)
classes+=(NewTrackProcess DeleteTrackProcess RestoreTrackProcess)
classes+=(AudioSystem AudioInterface)
classes+=(ALSAAudioSystem ALSAAudioInterface)
classes+=(IndentedOStream Date List)
files=()
files+=(src/main.cpp)

for class in "${classes[@]}"; do
	files+=(src/${class}.h)
	files+=(src/${class}.cpp)
	done

files+=(src/Message.h src/AudioTypes.h src/Amp.h)
files+=(html/index.html html/dawlet.css html/dawlet.js)
js_classes=(Keys Menus Actions SVGTemplate Track Clip Knob MouseTracker PopupMenu dB)
js_classes+=(RecordAction)
for class in "${js_classes[@]}"; do
	files+=(html/${class}.js)
	done
files+=(Makefile edit-all)

$EDITOR "${files[@]}"

